{{ config(
    materialized="table"
)}}

Select
PRODUCT_NAME,
PRODUCT_BARCODE,
PRODUCT_MANUFACTURER,
PRODUCT_BRAND,
PRODUCT_FMCG_CATEGORY,
PRODUCT_PACK_SIZE,
PRODUCT_PACK_TYPE
from DBT.RAW_FMCG.RAW_MP_ID_FMCG