/*SELECT
COUNT (DISTINCT product_barcode) as cnt,
PRODUCT_BARCODE,
PRODUCT_NAME,
PRODUCT_GS1_SEGMENT_DESC,
PRODUCT_GS1_FAMILY_DESC,
PRODUCT_GS1_CLASS_DESC,
RODUCT_GS1_BRICK_DESC as PRODUCT_GS1_BRICK_DESC,
PRODUCT_FMCG_CATEGORY,
PRODUCT_MANUFACTURER,
PRODUCT_BRAND,
PRODUCT_PACK_SIZE,
PRODUCT_PACK_TYPE
FROM {{source ('raw_fmcg_data','RAW_MP_ID_FMCG')}}
group by PRODUCT_NAME,PRODUCT_BARCODE,
PRODUCT_GS1_SEGMENT_DESC,
PRODUCT_GS1_FAMILY_DESC,
PRODUCT_GS1_CLASS_DESC,
RODUCT_GS1_BRICK_DESC,
PRODUCT_FMCG_CATEGORY,
PRODUCT_MANUFACTURER,
PRODUCT_BRAND,
PRODUCT_PACK_SIZE,
PRODUCT_PACK_TYPE*/


SELECT
PRODUCT_BARCODE,
PRODUCT_NAME,
PRODUCT_GS1_SEGMENT_DESC,
PRODUCT_GS1_FAMILY_DESC,
PRODUCT_GS1_CLASS_DESC,
PRODUCT_GS1_BRICK_DESC,
PRODUCT_FMCG_CATEGORY,
PRODUCT_MANUFACTURER,
PRODUCT_BRAND,
PRODUCT_PACK_SIZE,
PRODUCT_PACK_TYPE
FROM
(
SELECT
    PRODUCT_BARCODE,
PRODUCT_NAME,
PRODUCT_GS1_SEGMENT_DESC,
PRODUCT_GS1_FAMILY_DESC,
PRODUCT_GS1_CLASS_DESC,
RODUCT_GS1_BRICK_DESC as PRODUCT_GS1_BRICK_DESC,
PRODUCT_FMCG_CATEGORY,
PRODUCT_MANUFACTURER,
PRODUCT_BRAND,
PRODUCT_PACK_SIZE,
PRODUCT_PACK_TYPE,
ROW_NUMBER() OVER (PARTITION BY product_barcode ORDER BY product_barcode) RNO
FROM {{source ('raw_fmcg_data','RAW_MP_ID_FMCG')}}
)
WHERE RNO = 1